### PR TITLE
adding_references

### PR DESCRIPTION
**Pull request by jposada202020**
[X]   Verify that note in all the board.I2C references are present (Readme, examples and code)
[x]   Change hardware description `XXX`_  <Product Number>
[x]   Change Circuit Python references **Software and Dependencies:** 
[x]   If library uses SPI verify that digitalio import is included
[X]   Verify that learning guide is included
[X]   Verify that product is included

### CODE REVIEW

**Comment by jposada202020** [comment]
@kattni could you take a look, this was done when we were doing the documentation improvements but was left out for some reason. thanks :)

**Review by KeithTheEE — APPROVED** [review]
Looks good to me. All of the hyperlinks work, one to the sensor and two to the necessary libraries. The formatting looks clean as well.

**Comment by jposada202020** [comment]
@CrakeNotSnowman Thanks for the review :) really appreciated 👍🏼

**Comment by KeithTheEE** [comment]
No problem! Still learning what to look for with respect to the process--I'm still making my way through the learn guides, but I'm happy to help! Thanks for asking for it!

**Pull request merged**
